import sys
from stable_baselines3 import PPO

m = PPO.load(sys.argv[1], device="cpu")
sd = {k: v.cpu().numpy() for k, v in m.policy.state_dict().items()}
W = dict(w0=sd["mlp_extractor.policy_net.0.weight"], b0=sd["mlp_extractor.policy_net.0.bias"],
         w1=sd["mlp_extractor.policy_net.2.weight"], b1=sd["mlp_extractor.policy_net.2.bias"],
         w2=sd["action_net.weight"], b2=sd["action_net.bias"])
with open("policy_weights.py", "w") as f:
    f.write("# auto-generated by export_policy.py\nWEIGHTS = {\n")
    for k, v in W.items():
        f.write(f"    {k!r}: {v.tolist()!r},\n")
    f.write("}\n")
print("wrote policy_weights.py")